/*
 * ...
 */

Core.Codes = (function () {
  
  /*
   * Administrative Gender (HL7 V3)
   * http://phinvads.cdc.gov/vads/ViewValueSet.action?id=8DE75E17-176B-DE11-9B52-0015173D1785
   * OID: 2.16.840.1.113883.1.11.1
   */
  var GENDER_MAP = {
    'F': 'female',
    'M': 'male',
    'UN': 'undifferentiated'
  };
  
  /*
   * Marital Status (HL7)
   * http://phinvads.cdc.gov/vads/ViewValueSet.action?id=46D34BBC-617F-DD11-B38D-00188B398520
   * OID: 2.16.840.1.114222.4.11.809
   */
  var MARITAL_STATUS_MAP = {
    'N': 'annulled',
    'C': 'common law',
    'D': 'divorced',
    'P': 'domestic partner',
    'I': 'interlocutory',
    'E': 'legally separated',
    'G': 'living together',
    'M': 'married',
    'O': 'other',
    'R': 'registered domestic partner',
    'A': 'separated',
    'S': 'single',
    'U': 'unknown',
    'B': 'unmarried',
    'T': 'unreported',
    'W': 'widowed'
  };

  /*
   * Religious Affiliation (HL7 V3)
   * https://phinvads.cdc.gov/vads/ViewValueSet.action?id=6BFDBFB5-A277-DE11-9B52-0015173D1785
   * OID: 2.16.840.1.113883.1.11.19185
   */
  var RELIGION_MAP = {
    '1001': 'adventist',
    '1002': 'african',
    '1003': 'afro',
    '1004': 'agnosticism',
    '1005': 'anglican',
    '1006': 'animism',
    '1061': 'assembly',
    '1007': 'atheism',
    '1008': 'babi',
    '1009': 'baptist',
    '1010': 'bon',
    '1062': 'brethren',
    '1011': 'cao',
    '1012': 'celticism',
    '1013': 'christian',
    '1063': 'christian',
    '1064': 'church',
    '1065': 'church',
    '1014': 'confucianism',
    '1066': 'congregational',
    '1015': 'cyberculture',
    '1067': 'disciples',
    '1016': 'divination',
    '1068': 'eastern',
    '1069': 'episcopalian',
    '1070': 'evangelical',
    '1017': 'fourth',
    '1018': 'free',
    '1071': 'friends',
    '1072': 'full',
    '1019': 'gnosis',
    '1020': 'hinduism',
    '1021': 'humanism',
    '1022': 'independent',
    '1023': 'islam',
    '1024': 'jainism',
    '1025': 'jehovah',
    '1026': 'judaism',
    '1027': 'latter',
    '1028': 'lutheran',
    '1029': 'mahayana',
    '1030': 'meditation',
    '1031': 'messianic',
    '1073': 'methodist',
    '1032': 'mitraism',
    '1074': 'native',
    '1075': 'nazarene',
    '1033': 'new',
    '1034': 'non',
    '1035': 'occult',
    '1036': 'orthodox',
    '1037': 'paganism',
    '1038': 'pentecostal',
    '1076': 'presbyterian',
    '1039': 'process',
    '1077': 'protestant',
    '1078': 'protestant',
    '1079': 'reformed',
    '1040': 'reformed',
    '1041': 'roman',
    '1080': 'salvation',
    '1042': 'satanism',
    '1043': 'scientology',
    '1044': 'shamanism',
    '1045': 'shiite',
    '1046': 'shinto',
    '1047': 'sikism',
    '1048': 'spiritualism',
    '1049': 'sunni',
    '1050': 'taoism',
    '1051': 'theravada',
    '1081': 'unitarian',
    '1052': 'unitarian',
    '1082': 'united',
    '1053': 'universal',
    '1054': 'vajrayana',
    '1055': 'veda',
    '1056': 'voodoo',
    '1057': 'wicca',
    '1058': 'yaohushua',
    '1059': 'zen',
    '1060': 'zoroastrianism'
  };

  /*
   * Race & Ethnicity (HL7 V3)
   * Full list at http://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=2.16.840.1.113883.6.238
   * OID: 2.16.840.1.113883.6.238
   *
   * Abbreviated list closer to real usage at: (Race / Ethnicity)
   * https://phinvads.cdc.gov/vads/ViewValueSet.action?id=67D34BBC-617F-DD11-B38D-00188B398520
   * https://phinvads.cdc.gov/vads/ViewValueSet.action?id=35D34BBC-617F-DD11-B38D-00188B398520
   */
  var RACE_ETHNICITY_MAP = {
    '2028-9': 'asian',
    '2054-5': 'black',
    '2135-2': 'hispanic or latino',
    '2076-8': 'native',
    '2186-5': 'not hispanic or latino',
    '2131-1': 'other',
    '2106-3': 'white'
  };

  /*
   * Role (HL7 V3)
   * https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=2.16.840.1.113883.5.111
   * OID: 2.16.840.1.113883.5.111
   */
  var ROLE_MAP = {
    "acc": "accident site",
    "achfid":  "accreditation location identifier",
    "actmil":  "active duty military",
    "all": "allergy clinic",
    "amb": "ambulance",
    "amput":   "amputee clinic",
    "antibiot":    "antibiotic",
    "assist":  "assistive non-person living subject",
    "aunt":    "aunt",
    "b":   "blind",
    "bf":  "beef",
    "bill":    "billing contact",
    "bioth":   "biotherapeutic non-person living subject",
    "bl":  "broiler",
    "bmtc":    "bone marrow transplant clinic",
    "bmtu":    "bone marrow transplant unit",
    "br":  "breeder",
    "breast":  "breast clinic",
    "bro": "brother",
    "broinlaw":    "brother-in-law",
    "c":   "calibrator",
    "canc": "child and adolescent neurology clinic",
    "capc": "child and adolescent psychiatry clinic",
    "card": "ambulatory health care facilities; clinic/center; rehabilitation: cardiac facilities",
    "cas": "asylum seeker",
    "casm":    "single minor asylum seeker",
    "cath":    "cardiac catheterization lab",
    "cco": "clinical companion",
    "ccu": "coronary care unit",
    "chest":   "chest unit",
    "child":   "child",
    "chldadopt":   "adopted child",
    "chldfost":    "foster child",
    "chldinlaw":   "child in-law",
    "chr": "chronic care facility",
    "claim":   "claimant",
    "cn":  "national",
    "cnrp":    "non-country member without residence permit",
    "cnrpm":   "non-country member minor without residence permit",
    "co":  "companion",
    "coag":    "coagulation clinic",
    "cocben":  "continuity of coverage beneficiary",
    "comm":    "community location",
    "communitylaboratory": "community laboratory",
    "cousn":   "cousin",
    "cpca":    "permit card applicant",
    "crimevic":    "crime victim",
    "crp": "non-country member with residence permit",
    "crpm":    "non-country member minor with residence permit",
    "crs": "colon and rectal surgery clinic",
    "csc": "community service center",
    "cvdx":    "cardiovascular diagnostics or therapeutics unit",
    "da":  "dairy",
    "daddr":   "delivery address",
    "dau": "natural daughter",
    "dauadopt":    "adopted daughter",
    "dauc":    "daughter",
    "daufost": "foster daughter",
    "dauinlaw":    "daughter in-law",
    "dc":  "therapeutic class",
    "debr":    "debridement",
    "derm":    "dermatology clinic",
    "diffabl": "differently abled",
    "dompart": "domestic partner",
    "dpowatt": "durable power of attorney",
    "dr":  "draft",
    "du":  "dual",
    "dx":  "diagnostics or therapeutics unit",
    "e":   "electronic qc",
    "echo":    "echocardiography lab",
    "econ":    "emergency contact",
    "endo":    "endocrinology clinic",
    "endos":   "endoscopy lab",
    "enrolbkr":    "enrollment broker",
    "ent": "otorhinolaryngology clinic",
    "epil":    "epilepsy unit",
    "er":  "emergency room",
    "erl": "enrollment",
    "etu": "emergency trauma unit",
    "excest":  "executor of estate",
    "ext": "extended family member",
    "f":   "filler proficiency",
    "famdep":  "family dependent",
    "fammemb": "family member",
    "fi":  "fiber",
    "fmc": "family medicine clinic",
    "frnd":    "unrelated friend",
    "fstud":   "full-time student",
    "fth": "father",
    "fthinlaw":    "father-in-law",
    "fullins": "fully insured coverage sponsor",
    "g":   "group",
    "gach":    "hospitals; general acute care hospital",
    "gd":  "generic drug",
    "gdf": "generic drug form",
    "gds": "generic drug strength",
    "gdsf":    "generic drug strength form",
    "ggrfth":  "great grandfather",
    "ggrmth":  "great grandmother",
    "ggrprn":  "great grandparent",
    "gi":  "gastroenterology clinic",
    "gidx":    "gastroenterology diagnostics or therapeutics lab",
    "gim": "general internal medicine clinic",
    "grfth":   "grandfather",
    "grmth":   "grandmother",
    "grndchild":   "grandchild",
    "grnddau": "granddaughter",
    "grndson": "grandson",
    "grprn":   "grandparent",
    "gt":  "guarantor",
    "guadltm": "guardian ad lidem",
    "guard":   "guardian",
    "gyn": "gynecology clinic",
    "hand":    "hand clinic",
    "handic":  "handicapped dependent",
    "hbro":    "half-brother",
    "hd":  "hemodialysis unit",
    "hem": "hematology clinic",
    "hlab":    "hospital laboratory",
    "homehealth":  "home health",
    "hosp":    "hospital",
    "hpowatt": "healthcare power of attorney",
    "hrad":    "radiology unit",
    "hsib":    "half-sibling",
    "hsis":    "half-sister",
    "htn": "hypertension clinic",
    "hu":  "hospital unit",
    "husb":    "husband",
    "huscs":   "specimen collection site",
    "icu": "intensive care unit",
    "iec": "impairment evaluation center",
    "indig":   "member of an indigenous people",
    "infd":    "infectious disease clinic",
    "inj": "injured plaintiff",
    "injwkr":  "injured worker",
    "inlab":   "inpatient laboratory",
    "inpharm": "inpatient pharmacy",
    "inv": "infertility clinic",
    "jurid":   "jurisdiction location identifier",
    "l":   "pool",
    "laboratory":  "laboratory",
    "lochfid": "local location identifier",
    "ly":  "layer",
    "lymph":   "lympedema clinic",
    "maunt":   "maternalaunt",
    "mbl": "medical laboratory",
    "mcousn":  "maternalcousin",
    "mgdsf":   "manufactured drug strength form",
    "mgen":    "medical genetics clinic",
    "mggrfth": "maternalgreatgrandfather",
    "mggrmth": "maternalgreatgrandmother",
    "mggrprn": "maternalgreatgrandparent",
    "mgrfth":  "maternalgrandfather",
    "mgrmth":  "maternalgrandmother",
    "mgrprn":  "maternalgrandparent",
    "mhsp":    "military hospital",
    "mil": "military",
    "mobl":    "mobile unit",
    "mt":  "meat",
    "mth": "mother",
    "mthinlaw":    "mother-in-law",
    "mu":  "multiplier",
    "muncle":  "maternaluncle",
    "nbor":    "neighbor",
    "nbro":    "natural brother",
    "nccf":    "nursing or custodial care facility",
    "nccs":    "neurology critical care and stroke unit",
    "nchild":  "natural child",
    "neph":    "nephrology clinic",
    "nephew":  "nephew",
    "neur":    "neurology clinic",
    "nfth":    "natural father",
    "nfthf":   "natural father of fetus",
    "niece":   "niece",
    "nieneph": "niece/nephew",
    "nmth":    "natural mother",
    "nok": "next of kin",
    "nprn":    "natural parent",
    "ns":  "neurosurgery unit",
    "nsib":    "natural sibling",
    "nsis":    "natural sister",
    "o":   "operator proficiency",
    "ob":  "obstetrics clinic",
    "of":  "outpatient facility",
    "oms": "oral and maxillofacial surgery clinic",
    "oncl":    "medical oncology clinic",
    "oph": "opthalmology clinic",
    "optc":    "optometry clinic",
    "org": "organizational contact",
    "ortho":   "orthopedics clinic",
    "outlab":  "outpatient laboratory",
    "outpharm":    "outpatient pharmacy",
    "p":   "patient",
    "paincl":  "pain clinic",
    "pathologist": "pathologist",
    "paunt":   "paternalaunt",
    "payor":   "payor contact",
    "pc":  "primary care clinic",
    "pcousn":  "paternalcousin",
    "pedc":    "pediatrics clinic",
    "pedcard": "pediatric cardiology clinic",
    "pede":    "pediatric endocrinology clinic",
    "pedgi":   "pediatric gastroenterology clinic",
    "pedhem":  "pediatric hematology clinic",
    "pedho":   "pediatric oncology clinic",
    "pedicu":  "pediatric intensive care unit",
    "pedid":   "pediatric infectious disease clinic",
    "pedneph": "pediatric nephrology clinic",
    "pednicu": "pediatric neonatal intensive care unit",
    "pedrheum":    "pediatric rheumatology clinic",
    "pedu":    "pediatric unit",
    "pggrfth": "paternalgreatgrandfather",
    "pggrmth": "paternalgreatgrandmother",
    "pggrprn": "paternalgreatgrandparent",
    "pgrfth":  "paternalgrandfather",
    "pgrmth":  "paternalgrandmother",
    "pgrprn":  "paternalgrandparent",
    "ph":  "policy holder",
    "pharm":   "pharmacy",
    "phlebotomist":    "phlebotomist",
    "phu": "psychiatric hospital unit",
    "pl":  "pleasure",
    "pls": "plastic surgery clinic",
    "pod": "podiatry clinic",
    "powatt":  "power of attorney",
    "prc": "pain rehabilitation center",
    "prev":    "preventive medicine clinic",
    "prn": "parent",
    "prninlaw":    "parent in-law",
    "procto":  "proctology clinic",
    "proff":   "provider's office",
    "prog":    "program eligible",
    "pros":    "prosthodontics clinic",
    "psi": "psychology clinic",
    "pstud":   "part-time student",
    "psy": "psychiatry clinic",
    "psychf":  "psychatric care facility",
    "pt":  "patient",
    "ptres":   "patient's residence",
    "puncle":  "paternaluncle",
    "q":   "quality control",
    "r":   "replicate",
    "raddx":   "radiology diagnostics or therapeutics unit",
    "rado":    "radiation oncology unit",
    "rc":  "racing",
    "resprsn": "responsible party",
    "retiree": "retiree",
    "retmil":  "retired military",
    "rh":  "rehabilitation hospital",
    "rhat":    "addiction treatment center",
    "rheum":   "rheumatology clinic",
    "rhii":    "intellectual impairment center",
    "rhmad":   "parents with adjustment difficulties center",
    "rhpi":    "physical impairment center",
    "rhpih":   "physical impairment - hearing center",
    "rhpims":  "physical impairment - motor skills center",
    "rhpivs":  "physical impairment - visual skills center",
    "rhu": "rehabilitation hospital unit",
    "rhyad":   "youths with adjustment difficulties center",
    "rneu":    "neuroradiology unit",
    "room":    "roommate",
    "rtf": "residential treatment facility",
    "school":  "school",
    "scn": "screening",
    "see": "seeing",
    "self":    "self",
    "selfins": "self insured coverage sponsor",
    "sh":  "show",
    "sib": "sibling",
    "sibinlaw":    "sibling in-law",
    "sigothr": "significant other",
    "sis": "sister",
    "sisinlaw":    "sister-in-law",
    "sleep":   "sleep disorders unit",
    "snf": "skilled nursing facility",
    "sniff":   "sniffing",
    "son": "natural son",
    "sonadopt":    "adopted son",
    "sonc":    "son",
    "sonfost": "foster son",
    "soninlaw":    "son in-law",
    "spmed":   "sports medicine clinic",
    "spon":    "sponsored dependent",
    "spowatt": "special power of attorney",
    "sps": "spouse",
    "stpbro":  "stepbrother",
    "stpchld": "step child",
    "stpdau":  "stepdaughter",
    "stpfth":  "stepfather",
    "stpmth":  "stepmother",
    "stpprn":  "step parent",
    "stpsib":  "step sibling",
    "stpsis":  "stepsister",
    "stpson":  "stepson",
    "stud":    "student",
    "su":  "surgery clinic",
    "subject": "self",
    "surf":    "substance use rehabilitation facility",
    "thirdparty":  "third party",
    "tpa": "third party administrator",
    "tr":  "transplant clinic",
    "travel":  "travel and geographic medicine clinic",
    "trb": "tribal member",
    "umo": "utilization management organization",
    "uncle":   "uncle",
    "upc": "underage protection center",
    "uro": "urology clinic",
    "v":   "verifying",
    "vet": "veteran",
    "vl":  "veal",
    "ward":    "ward",
    "wife":    "wife",
    "wl":  "wool",
    "wnd": "wound clinic",
    "wo":  "working",
    "work":    "work site",
  };


  // copied from _.invert to avoid making browser users include all of underscore
  var invertKeys = function(obj) {
    var result = {};
    var keys = Object.keys(obj);
    for (var i = 0, length = keys.length; i < length; i++) {
      result[obj[keys[i]]] = keys[i];
    }
    return result;
  };

  var lookupFnGenerator = function(map) {
    return function(key) {
      return map[key] || null;
    };
  };
  var reverseLookupFnGenerator = function(map) {
    return function(key) {
      var invertedMap = invertKeys(map);
      key = key.toLowerCase();
      return invertedMap[key] || null;
    };
  };
  
  
  return {
    gender: lookupFnGenerator(GENDER_MAP),
    reverseGender: reverseLookupFnGenerator(GENDER_MAP),
    maritalStatus: lookupFnGenerator(MARITAL_STATUS_MAP),
    reverseMaritalStatus: reverseLookupFnGenerator(MARITAL_STATUS_MAP),
    religion: lookupFnGenerator(RELIGION_MAP),
    reverseReligion: reverseLookupFnGenerator(RELIGION_MAP),
    raceEthnicity: lookupFnGenerator(RACE_ETHNICITY_MAP),
    reverseRaceEthnicity: reverseLookupFnGenerator(RACE_ETHNICITY_MAP),
    role: lookupFnGenerator(ROLE_MAP),
    reverseRole: reverseLookupFnGenerator(ROLE_MAP)
  };
  
})();
