
class String
  def error
    # red => \e[0;31
    # red/bold => \e[1;31m
    "\n\e[0;31m#{self}\e[0m"
  end
  def task
    "\e[1;34m#{self}\e[0m"
  end
  def success
    "\e[0;32m#{self}\e[0m"
  end
end

desc "Deploy to Heroku"
task :deploy do
  
  puts "", "Adding to git...".task
  puts `git add .`
  puts `git status`
  puts `git commit -am "Updates"`
  
  puts "", "Pushing to Heroku...".task, ""
  `git push heroku master`
  
  puts "", "Done!".task, ""
  
end

task :default => :deploy
